"""empty message

Revision ID: 62bae0f93f7e
Revises: fde90ae6d9e7
Create Date: 2023-07-17 02:22:24.204037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bae0f93f7e'
down_revision = 'fde90ae6d9e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_run', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('next_run', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('next_run')
        batch_op.drop_column('last_run')

    # ### end Alembic commands ###
