"""empty message

Revision ID: c99b22188c6f
Revises: 
Create Date: 2023-07-24 02:00:46.113938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99b22188c6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprinkler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_task_sprinkler',
    sa.Column('watering_task_id', sa.Integer(), nullable=False),
    sa.Column('sprinkler_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sprinkler_id'], ['sprinkler.id'], ),
    sa.ForeignKeyConstraint(['watering_task_id'], ['watering_task.id'], ),
    sa.PrimaryKeyConstraint('watering_task_id', 'sprinkler_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watering_task_sprinkler')
    op.drop_table('watering_task')
    op.drop_table('sprinkler')
    op.drop_table('schedule')
    # ### end Alembic commands ###
