"""adjusting the job and schedule relationships

Revision ID: d39e88255d38
Revises: 
Create Date: 2023-10-28 11:48:47.971363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39e88255d38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('custom_days', sa.String(length=13), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprinkler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('run_datetime', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('sprinkler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='fk_job_schedule', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprinkler_id'], ['sprinkler.id'], name='fk_job_sprinkler', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('run_datetime', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('completed_time', sa.DateTime(), nullable=True),
    sa.Column('sprinkler_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='fk_joblog_schedule'),
    sa.ForeignKeyConstraint(['sprinkler_id'], ['sprinkler.id'], name='fk_joblog_sprinkler'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watering_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('sprinkler_id', sa.Integer(), nullable=False),
    sa.Column('task_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], name='fk_wateringtask_schedule', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprinkler_id'], ['sprinkler.id'], name='fk_wateringtask_sprinkler'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watering_task')
    op.drop_table('job_log')
    op.drop_table('job')
    op.drop_table('sprinkler')
    op.drop_table('schedule')
    # ### end Alembic commands ###
